# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop

  labels:
    component: shipping
    project: roboshop
    tier: application

spec:
  replicas: {{ .Values.deployment.replicas }}
# These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      component: shipping
      project: roboshop
      tier: application
  # This is pod definition
  template:
    metadata:
      labels:
        component: shipping
        project: roboshop
        tier: application

    spec:
      containers:
      - name: shipping
        image: "{{ .Values.deployment.image }}:{{ .Values.deployment.imageVersion }}" #sangala2025/shipping:v1
        resources:
          requests:
            cpu: "150m"
            memory: "256Mi"

          limits:
            cpu: "350m"
            memory: "700Mi"

        envFrom:
        - configMapRef:
            name: shipping
