# Service
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop

  labels:
    component: shipping
    project: roboshop
    tier: application

spec:

  selector:
    component: shipping
    project: roboshop
    tier: application

  ports:
  - protocol: TCP
    port: 8080 # service port
    targetPort: {{ .Values.deployment.targetPort}} #8080  container port
